{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPiRCa2agv++y8sXv42gzq9",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Hawino/kasir-sederhana/blob/main/Main.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#Library untuk menginstal module pembuat Tabel\n",
        "!pip install tabulate\n",
        "from tabulate import tabulate"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "7XRiaApn3Opr",
        "outputId": "e2d7d5db-f1d9-4b66-8f66-1fa66423cdc1"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (0.9.0)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "S0Bmh1JU9_b9",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "387d173d-f0b9-4e58-b2da-e3586d16864e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 1\n",
            "------------------------------------------------------------\n",
            "Masukkan Nama, Jumlah & Harga Barang\n",
            "------------------------------------------------------------\n",
            "Input Nama Barang: ayam goreng\n",
            "Input Jumlah Barang : 2\n",
            "Input Harga : 20000\n",
            "Barang di Keranjang saat ini: [('ayam goreng', 2, 20000)]\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 1\n",
            "------------------------------------------------------------\n",
            "Masukkan Nama, Jumlah & Harga Barang\n",
            "------------------------------------------------------------\n",
            "Input Nama Barang: pasta gigi\n",
            "Input Jumlah Barang : 2\n",
            "Input Harga : 15000\n",
            "Barang di Keranjang saat ini: [('ayam goreng', 2, 20000), ('pasta gigi', 2, 15000)]\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 5\n",
            "------------------------------------------------------------\n",
            "Masukkan Nama Barang yang ingin dihapus\n",
            "------------------------------------------------------------\n",
            "Input Nama Barang: pasta gigi\n",
            "Barang di Keranjang saat ini: [('ayam goreng', 2, 20000)]\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 6\n",
            "Semua Barang di keranjang berhasil dihapus\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 1\n",
            "------------------------------------------------------------\n",
            "Masukkan Nama, Jumlah & Harga Barang\n",
            "------------------------------------------------------------\n",
            "Input Nama Barang: ayam goreng\n",
            "Input Jumlah Barang : 2\n",
            "Input Harga : 20000\n",
            "Barang di Keranjang saat ini: [('ayam goreng', 2, 20000)]\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 1\n",
            "------------------------------------------------------------\n",
            "Masukkan Nama, Jumlah & Harga Barang\n",
            "------------------------------------------------------------\n",
            "Input Nama Barang: pasta gigi\n",
            "Input Jumlah Barang : 3\n",
            "Input Harga : 15000\n",
            "Barang di Keranjang saat ini: [('ayam goreng', 2, 20000), ('pasta gigi', 3, 15000)]\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 1\n",
            "------------------------------------------------------------\n",
            "Masukkan Nama, Jumlah & Harga Barang\n",
            "------------------------------------------------------------\n",
            "Input Nama Barang: mainan mobil\n",
            "Input Jumlah Barang : 1\n",
            "Input Harga : 250000\n",
            "Barang di Keranjang saat ini: [('ayam goreng', 2, 20000), ('pasta gigi', 3, 15000), ('mainan mobil', 1, 250000)]\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 7\n",
            "------------------------------------------------------------\n",
            "List semua Barang yang ada di Keranjang Anda\n",
            "------------------------------------------------------------\n",
            "Nama Item       Jumlah Item    Harga Satuan    Total Harga\n",
            "------------  -------------  --------------  -------------\n",
            "ayam goreng               2           20000          40000\n",
            "pasta gigi                3           15000          45000\n",
            "mainan mobil              1          250000         250000\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 8\n",
            "------------------------------------------------------------\n",
            "Total Belanja Anda\n",
            "------------------------------------------------------------\n",
            "Barang yang dibeli: [('ayam goreng', 2, 20000), ('pasta gigi', 3, 15000), ('mainan mobil', 1, 250000)]\n",
            "Total belanjaan Anda: Rp308200.0 setelah mendapatkan Diskon (8.0%): Rp26800.0\n",
            "\n",
            "------------------------------------------------------------\n",
            "SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\n",
            "------------------------------------------------------------\n",
            "1. Masukkan Barang Belanja \n",
            "2. Update Nama Barang Belanja\n",
            "3. Update Jumlah Barang Belanja\n",
            "4. Update Harga Barang Belanja \n",
            "5. Menghapus Barang Belanja\n",
            "6. Menghapus Semua Barang di Keranjang (RESET)\n",
            "7. Check Keranjang Belanja\n",
            "8. Total Belanja\n",
            "9. Exit\n",
            "\n",
            "Masukkan Nomor Menu : 9\n",
            "------------------------------------------------------------\n",
            "Terima kasih telah mengunjungi Supermarket Kami.\n",
            "------------------------------------------------------------\n"
          ]
        }
      ],
      "source": [
        "class Transaction():\n",
        "  \"\"\"\n",
        "  Class untuk mensimulasikan transaksi pembelian.\n",
        "\n",
        "  Atribut:\n",
        "    nama_item: List yang berisi nama item yang dibeli.\n",
        "    jumlah_item: List yang berisi jumlah item yang dibeli.\n",
        "    harga_item: List yang berisi harga item yang dibeli.\n",
        "  \"\"\"\n",
        "  def __init__(self):\n",
        "    self.nama_item =[]\n",
        "    self.jumlah_item =[]\n",
        "    self.harga_item =[]\n",
        "    self.total_harga =[]\n",
        "\n",
        "  def add_item(self):\n",
        "    \"\"\"\n",
        "  Menambahkan item baru ke transaksi.\n",
        "\n",
        "  Args:\n",
        "    nama: Nama item yang ingin ditambahkan.\n",
        "    jumlah: Jumlah item yang ingin ditambahkan.\n",
        "    harga: Harga item yang ingin ditambahkan.\n",
        "\n",
        "  Returns:\n",
        "    List barang belanja yang sudah diinput.\n",
        "    \"\"\"\n",
        "    print(\"-\"*60)\n",
        "    print(\"Masukkan Nama, Jumlah & Harga Barang\")\n",
        "    print(\"-\"*60)\n",
        "\n",
        "    nama = input(\"Input Nama Barang: \")\n",
        "    nama_kecil = str(nama.lower()) #Mencegah format input \"Nama Item\" yang tidak sesuai\n",
        "\n",
        "    jumlah = int(input(\"Input Jumlah Barang : \"))\n",
        "    try: #Memberi info jika input \"Jumlah Item\" yang tidak sesuai\n",
        "      int(jumlah)\n",
        "    except ValueError:\n",
        "      print(\"Jumlah Item yang dimasukan harus Angka\")\n",
        "      jumlah = int(input(\"Input Jumlah Barang : \"))\n",
        "\n",
        "    harga = int(input(\"Input Harga : \"))\n",
        "    try: #Memberi info jika input \"Harga Item\" yang tidak sesuai\n",
        "      int(harga)\n",
        "    except ValueError:\n",
        "      print(\"Harga Item yang dimasukan harus Angka\")\n",
        "      harga = int(input(\"Input Harga : \"))\n",
        "\n",
        "    self.nama_item.append(nama_kecil) #Memasukan data input ke list\n",
        "    self.jumlah_item.append(jumlah)\n",
        "    self.harga_item.append(harga)\n",
        "\n",
        "    self.semua_order=list(zip(self.nama_item, self.jumlah_item, self.harga_item)) #Menggabungkan list nama, jumlah & harga\n",
        "    print(f'Barang di Keranjang saat ini: {self.semua_order}')\n",
        "\n",
        "    self.menu()\n",
        "\n",
        "\n",
        "  def update_nama_item(self):\n",
        "    \"\"\"\n",
        "  Mengubah nama item yang sudah ada.\n",
        "\n",
        "  Args:\n",
        "    nama: Nama item yang ingin diubah.\n",
        "    update_nama: Nama baru untuk item.\n",
        "\n",
        "  Returns:\n",
        "    List barang belanja yang sudah diupdate itemnya.\n",
        "    \"\"\"\n",
        "    print(\"-\"*60)\n",
        "    print(\"Masukkan Nama Barang yang ingin diupdate Namanya\")\n",
        "    print(\"-\"*60)\n",
        "\n",
        "    nama = input(\"Input Nama Barang: \")\n",
        "    nama_kecil = str(nama.lower()) #Mencegah format input \"Nama Item\" yang tidak sesuai\n",
        "\n",
        "    update_nama = input(\"Input Nama Barang yang baru: \")\n",
        "    update_kecil = str(update_nama.lower())\n",
        "\n",
        "    for i in range(len(self.nama_item)): #Program mengganti \"Nama Item\"\n",
        "      if self.nama_item[i] == nama_kecil:\n",
        "        self.nama_item[i] = update_kecil\n",
        "        self.semua_order=list(zip(self.nama_item, self.jumlah_item, self.harga_item))\n",
        "        print(f'Barang di Keranjang saat ini: {self.semua_order}')\n",
        "      elif not nama_kecil in self.nama_item: #Memberikan info jika \"Nama Item\" yang diinput salah\n",
        "        print(f\"Barang '{nama_kecil}' tidak ada di transaksi sebelumnya.\")\n",
        "        self.menu()\n",
        "\n",
        "    self.menu()\n",
        "\n",
        "  def update_jumlah_item(self):\n",
        "    \"\"\"\n",
        "  Mengubah jumlah item yang sudah ada.\n",
        "\n",
        "  Args:\n",
        "    nama_item: Nama item yang ingin diubah jumlahnya.\n",
        "    jumlah_baru: Jumlah baru untuk item.\n",
        "\n",
        "  Returns:\n",
        "    List barang belanja yang sudah diupdate jumlahnya.\n",
        "    \"\"\"\n",
        "    print(\"-\"*60)\n",
        "    print(\"Masukkan Nama Barang yang ingin diupdate Jumlahnya\")\n",
        "    print(\"-\"*60)\n",
        "\n",
        "    nama = input(\"Input Nama Barang: \")\n",
        "    nama_kecil = str(nama.lower()) #Mencegah format input \"Nama Item\" yang tidak sesuai\n",
        "\n",
        "    jumlah_baru = int(input(\"Input Jumlah Barang baru: \"))\n",
        "    try: #Code untuk memberi info input \"Jumlah Item\" yang tidak sesuai\n",
        "      int(jumlah_baru)\n",
        "    except ValueError:\n",
        "      print(\"Jumlah Barang Baru yang dimasukan harus Angka\")\n",
        "      jumlah_baru = input(\"Input Jumlah Barang baru: \")\n",
        "\n",
        "    for i in range(len(self.nama_item)): #Program mengganti \"Jumlah Item\"\n",
        "      if self.nama_item[i] == nama_kecil:\n",
        "        self.jumlah_item[i] = jumlah_baru\n",
        "        self.semua_order=list(zip(self.nama_item, self.jumlah_item, self.harga_item))\n",
        "        print(f'Barang di Keranjang saat ini: {self.semua_order}')\n",
        "      elif not nama_kecil in self.nama_item: #Memberikan info jika \"Nama Item\" yang diinput salah\n",
        "        print(f\"Barang '{nama_kecil}' tidak ada di transaksi sebelumnya.\")\n",
        "        self.menu()\n",
        "\n",
        "    self.menu()\n",
        "\n",
        "\n",
        "  def update_harga_item(self):\n",
        "    \"\"\"\n",
        "  Mengubah harga item yang sudah ada.\n",
        "\n",
        "  Args:\n",
        "    nama_item: Nama item yang ingin diubah harganya.\n",
        "    harga_baru: Harga baru untuk item.\n",
        "\n",
        "  Returns:\n",
        "    List barang belanja yang sudah diupdate harganya.\n",
        "    \"\"\"\n",
        "    print(\"-\"*60)\n",
        "    print(\"Masukkan Nama Barang yang ingin diupdate Harganya\")\n",
        "    print(\"-\"*60)\n",
        "\n",
        "    nama = input(\"Input Nama Barang: \")\n",
        "    nama_kecil = str(nama.lower()) #Mencegah format input \"Nama Item\" yang tidak sesuai\n",
        "\n",
        "    harga_baru = int(input(\"Input Harga Barang baru: \"))\n",
        "    try: #Code untuk memberi info input \"Harga Item\" yang tidak sesuai\n",
        "      int(harga_baru)\n",
        "    except ValueError:\n",
        "      print(\"Harga Barang Baru yang dimasukan harus Angka\")\n",
        "      harga_baru = input(\"Input Harga Barang baru: \")\n",
        "\n",
        "    for i in range(len(self.nama_item)): #Program mengganti \"Harga Item\"\n",
        "      if self.nama_item[i] == nama_kecil:\n",
        "        self.harga_item[i] = harga_baru\n",
        "        self.semua_order=list(zip(self.nama_item, self.jumlah_item, self.harga_item))\n",
        "        print(f'Barang di Keranjang saat ini: {self.semua_order}')\n",
        "      elif not nama_kecil in self.nama_item: #Memberikan info jika \"Nama Item\" yang diinput salah\n",
        "        print(f\"Barang '{nama_kecil}' tidak ada di transaksi sebelumnya.\")\n",
        "        self.menu()\n",
        "\n",
        "    self.menu()\n",
        "\n",
        "\n",
        "  def delete_item(self):\n",
        "    \"\"\"\n",
        "  Menghapus item dari transaksi.\n",
        "\n",
        "  Args:\n",
        "    nama_item: Nama item yang ingin dihapus.\n",
        "\n",
        "  Returns:\n",
        "    List barang belanja setelah ada item yang dihapus.\n",
        "    \"\"\"\n",
        "    print(\"-\"*60)\n",
        "    print(\"Masukkan Nama Barang yang ingin dihapus\")\n",
        "    print(\"-\"*60)\n",
        "\n",
        "    nama = input(\"Input Nama Barang: \")\n",
        "    nama_kecil = str(nama.lower()) #Mencegah format input \"Nama Item\" yang tidak sesuai\n",
        "\n",
        "    for i in range(len(self.nama_item)): #Program menghapus \"Nama, Jumlah, Harga dari 1 Item\"\n",
        "      if self.nama_item[i] == nama_kecil:\n",
        "        self.nama_item.pop(i)\n",
        "        self.jumlah_item.pop(i)\n",
        "        self.harga_item.pop(i)\n",
        "        self.semua_order=list(zip(self.nama_item, self.jumlah_item, self.harga_item))\n",
        "        print(f'Barang di Keranjang saat ini: {self.semua_order}')\n",
        "      elif not nama_kecil in self.nama_item: #Memberikan info jika \"Nama Item\" yang diinput salah\n",
        "        print(f\"Barang '{nama_kecil}' tidak ada di transaksi sebelumnya.\")\n",
        "        self.menu()\n",
        "\n",
        "    self.menu()\n",
        "\n",
        "\n",
        "  def reset_transaction(self):\n",
        "    \"\"\"\n",
        "  Menghapus semua item dari transaksi.\n",
        "\n",
        "  Args:\n",
        "    None.\n",
        "\n",
        "  Returns:\n",
        "    None\n",
        "    \"\"\"\n",
        "    self.nama_item.clear() #Program menghapus semua Item\n",
        "    self.jumlah_item.clear()\n",
        "    self.harga_item.clear()\n",
        "    print('Semua Barang di keranjang berhasil dihapus')\n",
        "    self.menu()\n",
        "\n",
        "  def check_order(self):\n",
        "    \"\"\"\n",
        "  Melihat semua item dari transaksi dalam bentuk tabel.\n",
        "\n",
        "  Args:\n",
        "    None.\n",
        "\n",
        "  Returns:\n",
        "    Tabel list semua barang belanjaan, jumlah barang, harga/unit, total biaya/unit\n",
        "    \"\"\"\n",
        "    self.total_harga = [x * y for x, y in zip(self.jumlah_item, self.harga_item)] #Membuat variabel tambahan, Total Harga/Satuan\n",
        "    self.semua_order=list(zip(self.nama_item, self.jumlah_item, #Menggabungkan semua List \"Nama Item\",\"Jumlah Item\",\"Harga Satuan\",\"Total Harga\"\n",
        "                              self.harga_item, self.total_harga))\n",
        "    print(\"-\"*60)\n",
        "    print(\"List semua Barang yang ada di Keranjang Anda\")\n",
        "    print(\"-\"*60)\n",
        "    print(tabulate(self.semua_order,headers=[\"Nama Item\",\"Jumlah Item\",\"Harga Satuan\",\"Total Harga\"])) #Membuat Tabel\n",
        "\n",
        "    self.menu()\n",
        "\n",
        "  def total_price(self):\n",
        "    \"\"\"\n",
        "  Menghitung Total Harga list barang belanjaan.\n",
        "\n",
        "  Args:\n",
        "    None.\n",
        "\n",
        "  Returns:\n",
        "    Total harga dan list barang belanjaan.\n",
        "    \"\"\"\n",
        "    print(\"-\"*60)\n",
        "    print(\"Total Belanja Anda\")\n",
        "    print(\"-\"*60)\n",
        "\n",
        "    total = 0 #Menghitung seluruh Total Harga\n",
        "    for i in range(len(self.jumlah_item)):\n",
        "      total += ((self.jumlah_item[i])*(self.harga_item[i]))\n",
        "\n",
        "    self.semua_order = list(zip(self.nama_item, self.jumlah_item, self.harga_item)) #Menggabungkan semua List \"Nama Item\",\"Jumlah Item\",\"Harga Satuan\"\n",
        "    print(f'Barang yang dibeli: {self.semua_order}')\n",
        "\n",
        "    if 0 <= total < 200_000: #Menentukan Diskon yang didapatkan dan Total Harga Akhir\n",
        "      print(f'Total belanjaan Anda: Rp{total}')\n",
        "    elif 200_000 <= total < 300_000:\n",
        "      diskon = 0.05\n",
        "      total_akhir = total - (total*diskon)\n",
        "      print(f'Total belanjaan Anda: Rp{total_akhir} setelah mendapatkan Diskon ({diskon*100}%): Rp{total*diskon}')\n",
        "    elif 300_000 <= total < 500_000:\n",
        "      diskon = 0.08\n",
        "      total_akhir = total - (total*diskon)\n",
        "      print(f'Total belanjaan Anda: Rp{total_akhir} setelah mendapatkan Diskon ({diskon*100}%): Rp{total*diskon}')\n",
        "    elif total > 500_000:\n",
        "      diskon = 0.1\n",
        "      total_akhir = total - (total*diskon)\n",
        "      print(f'Total belanjaan Anda: Rp{total_akhir} setelah mendapatkan Diskon ({diskon*100}%): Rp{total*diskon}')\n",
        "\n",
        "    self.menu()\n",
        "\n",
        "  def menu(self):\n",
        "    print()\n",
        "    print(\"-\"*60)\n",
        "    print(\"SELAMAT DATANG DI SELF SERVICE CASHIER PACMANN\")\n",
        "    print(\"-\"*60)\n",
        "    print(\"1. Masukkan Barang Belanja \")\n",
        "    print(\"2. Update Nama Barang Belanja\")\n",
        "    print(\"3. Update Jumlah Barang Belanja\")\n",
        "    print(\"4. Update Harga Barang Belanja \")\n",
        "    print(\"5. Menghapus Barang Belanja\")\n",
        "    print(\"6. Menghapus Semua Barang di Keranjang (RESET)\")\n",
        "    print(\"7. Check Keranjang Belanja\")\n",
        "    print(\"8. Total Belanja\")\n",
        "    print(\"9. Exit\\n\")\n",
        "\n",
        "    choice = int(input('Masukkan Nomor Menu : '))\n",
        "\n",
        "    try:\n",
        "      if choice == 1:\n",
        "        self.add_item()\n",
        "      elif choice == 2:\n",
        "        self.update_nama_item()\n",
        "      elif choice == 3:\n",
        "        self.update_jumlah_item()\n",
        "      elif choice == 4:\n",
        "        self.update_harga_item()\n",
        "      elif choice == 5:\n",
        "        self.delete_item()\n",
        "      elif choice == 6:\n",
        "        self.reset_transaction()\n",
        "      elif choice == 7:\n",
        "        self.check_order()\n",
        "      elif choice == 8:\n",
        "        self.total_price()\n",
        "      elif choice == 9:\n",
        "        print(\"-\"*60)\n",
        "        print(\"Terima kasih telah mengunjungi Supermarket Kami.\")\n",
        "        print(\"-\"*60)\n",
        "        pass\n",
        "    except ValueError:\n",
        "      print(\"Input Anda salah.\\n\")\n",
        "      self.menu()\n",
        "\n",
        "\n",
        "start = Transaction()\n",
        "start.menu()\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "kcj_DFQu-Z1B"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "Transaction()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ModKVMUT2QDl",
        "outputId": "29d886eb-062a-4a07-8749-92f3264940ff"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<__main__.Transaction at 0x7a912f0d74c0>"
            ]
          },
          "metadata": {},
          "execution_count": 35
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "avORCNCd2SQ6"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}